version: "3.3"

services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_${APP_NAME}
    restart: unless-stopped
    tty: true
    networks:
      - go-blogs

  mariadb:
    image: mariadb:latest
    container_name: mariadb_${APP_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "3001:3306"
    environment:
      MARIADB_ROOT_PASSWORD:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'true'
    volumes:
      - ./mysql_dbs:/var/lib/mysql/
      - ./mysql.cnf:/etc/mysql/my.cnf
    networks:
      - go-blogs

  nginx:
    image: nginx:1.21.5-alpine
    container_name: nginx_${APP_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - "1003:80"
      - "2003:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - go-blogs

networks:
  go-blogs:
    driver: bridge